/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/island.glb -t -r public 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Circle015: THREE.Mesh
    Circle016: THREE.Mesh
    Circle017: THREE.Mesh
    Circle018: THREE.Mesh
    Circle019: THREE.Mesh
    Circle020: THREE.Mesh
    Circle021: THREE.Mesh
    Circle022: THREE.Mesh
    Icosphere014: THREE.Mesh
    Icosphere015: THREE.Mesh
    Icosphere016: THREE.Mesh
    Icosphere017: THREE.Mesh
    Icosphere018: THREE.Mesh
    Icosphere019: THREE.Mesh
    Icosphere020: THREE.Mesh
    Icosphere021: THREE.Mesh
    Icosphere022: THREE.Mesh
    Icosphere023: THREE.Mesh
    Icosphere024: THREE.Mesh
    Circle023: THREE.Mesh
    Circle024: THREE.Mesh
    Circle025: THREE.Mesh
    Circle026: THREE.Mesh
    Circle027: THREE.Mesh
    Circle028: THREE.Mesh
    Circle029: THREE.Mesh
    Icosphere025: THREE.Mesh
    Icosphere026: THREE.Mesh
    Icosphere027: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
  }
  materials: {
    Dirt: THREE.MeshBasicMaterial
    Stones: THREE.MeshBasicMaterial
    Grass: THREE.MeshBasicMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/island.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle015.geometry} material={materials.Dirt} />
      <mesh geometry={nodes.Circle016.geometry} material={materials.Dirt} />
      <mesh geometry={nodes.Circle017.geometry} material={materials.Dirt} position={[0, 0.209, 0]} />
      <mesh geometry={nodes.Circle018.geometry} material={materials.Dirt} />
      <mesh geometry={nodes.Circle019.geometry} material={materials.Dirt} position={[0, -0.267, 0]} />
      <mesh geometry={nodes.Circle020.geometry} material={materials.Dirt} position={[0, -0.455, 0]} />
      <mesh geometry={nodes.Circle021.geometry} material={materials.Dirt} />
      <mesh geometry={nodes.Circle022.geometry} material={materials.Dirt} />
      <mesh geometry={nodes.Icosphere014.geometry} material={materials.Stones} />
      <mesh geometry={nodes.Icosphere015.geometry} material={materials.Stones} />
      <mesh geometry={nodes.Icosphere016.geometry} material={materials.Stones} />
      <mesh geometry={nodes.Icosphere017.geometry} material={materials.Stones} position={[0, -0.164, 0]} />
      <mesh geometry={nodes.Icosphere018.geometry} material={materials.Stones} />
      <mesh geometry={nodes.Icosphere019.geometry} material={materials.Stones} />
      <mesh geometry={nodes.Icosphere020.geometry} material={materials.Stones} />
      <mesh geometry={nodes.Icosphere021.geometry} material={materials.Stones} position={[0, 0.086, 0]} />
      <mesh geometry={nodes.Icosphere022.geometry} material={materials.Stones} />
      <mesh geometry={nodes.Icosphere023.geometry} material={materials.Stones} />
      <mesh geometry={nodes.Icosphere024.geometry} material={materials.Stones} />
      <mesh geometry={nodes.Circle023.geometry} material={materials.Grass} />
      <mesh geometry={nodes.Circle024.geometry} material={materials.Grass} position={[0, -0.267, 0]} />
      <mesh geometry={nodes.Circle025.geometry} material={materials.Grass} position={[0, 0.209, 0]} />
      <mesh geometry={nodes.Circle026.geometry} material={materials.Grass} position={[0, -0.455, 0]} />
      <mesh geometry={nodes.Circle027.geometry} material={materials.Grass} />
      <mesh geometry={nodes.Circle028.geometry} material={materials.Grass} />
      <mesh geometry={nodes.Circle029.geometry} material={materials.Grass} />
      <mesh geometry={nodes.Icosphere025.geometry} material={materials.Stones} position={[3.993, -1.076, -0.897]} />
      <mesh geometry={nodes.Icosphere026.geometry} material={materials.Stones} position={[3.995, -0.842, 0.735]} />
      <mesh geometry={nodes.Icosphere027.geometry} material={materials.Stones} position={[2.278, -0.842, 3.02]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Stones} position={[4.206, 1.556, -2.295]} rotation={[-0.082, 0.411, -0.363]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Stones} position={[-2.846, 1.242, 2.167]} rotation={[3.129, 0.315, 2.724]} />
    </group>
  )
}

useGLTF.preload('/island.glb')
