/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/DystopianIcon.glb -t -r public 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Patrol: THREE.Mesh
  }
  materials: {
    Patrol: THREE.MeshStandardMaterial
  }
}

export function DystopianIcon(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/DystopianIcon.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Patrol.geometry} material={materials.Patrol} />
    </group>
  )
}

useGLTF.preload('/DystopianIcon.glb')
