/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/Panels.glb -t -r public 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Models: THREE.Mesh
    Skills: THREE.Mesh
    Projects: THREE.Mesh
    Models_Reverse: THREE.Mesh
    Skills_Reverse: THREE.Mesh
    Projects_Reverse: THREE.Mesh
  }
  materials: {}
}

export function usePanels() {
  const { nodes } = useGLTF('/Panels.glb') as GLTFResult
  return { nodes }
}